import type { Property, Project, Market, Testimonial, Stats } from './types';

/* ─── Featured Properties ────────────────────────────────────────────────────── */

export const FEATURED_PROPERTIES: Property[] = [
  {
    id: 'prop-001',
    title: 'Palm Jumeirah Signature Villa',
    price: 14500000,
    priceFormatted: '$14.5M',
    currency: 'USD',
    location: {
      city: 'Dubai',
      country: 'UAE',
      neighborhood: 'Palm Jumeirah',
    },
    type: 'Villa',
    beds: 7,
    baths: 9,
    sqm: 1420,
    status: 'resale',
    isOffPlan: false,
    description:
      'A spectacular beachfront villa on the iconic Palm Jumeirah, featuring floor-to-ceiling glazing and direct private beach access with panoramic Arabian Gulf views. Impeccably designed interiors blend contemporary Italian furnishings with bespoke stone and timber finishes throughout six opulent levels.',
    mainImage: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800',
    images: [
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800',
    ],
    amenities: [
      'Private Beach',
      'Infinity Pool',
      'Home Cinema',
      'Smart Home',
      'Boat Dock',
      'Gym & Spa',
      'Staff Quarters',
      'Wine Cellar',
    ],
    isLuxury: true,
    isFeatured: true,
    coordinates: { lat: 25.1124, lng: 55.139 },
  },
  {
    id: 'prop-002',
    title: 'Creek Harbour Sky Residences',
    price: 4200000,
    priceFormatted: '$4.2M',
    currency: 'USD',
    location: {
      city: 'Dubai',
      country: 'UAE',
      neighborhood: 'Dubai Creek Harbour',
    },
    type: 'Penthouse',
    beds: 4,
    baths: 5,
    sqm: 610,
    status: 'pre-construction',
    isOffPlan: true,
    completionYear: 2027,
    developer: 'Emaar Properties',
    description:
      'Crowning the tallest residential tower at Dubai Creek Harbour, this ultra-premium penthouse commands uninterrupted views of the Dubai skyline and the glittering Creek. Interiors by Versace Home marry bespoke marble detailing with cutting-edge home automation for a lifestyle without compromise.',
    mainImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800',
      'https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=800',
    ],
    amenities: [
      'Sky Pool',
      'Concierge 24/7',
      'Private Lift',
      'Rooftop Terrace',
      'Valet Parking',
      'Business Lounge',
      'Wellness Center',
    ],
    isLuxury: true,
    isFeatured: true,
    coordinates: { lat: 25.198, lng: 55.354 },
  },
  {
    id: 'prop-003',
    title: 'Star Island Waterfront Estate',
    price: 32000000,
    priceFormatted: '$32M',
    currency: 'USD',
    location: {
      city: 'Miami',
      country: 'USA',
      neighborhood: 'Star Island',
    },
    type: 'Estate',
    beds: 9,
    baths: 12,
    sqm: 2850,
    status: 'resale',
    isOffPlan: false,
    description:
      'Set on over an acre of lush grounds on the most exclusive private island in Miami, this architectural masterpiece offers 270-degree Biscayne Bay vistas and a private deepwater dock accommodating yachts up to 120 feet. Designed by Arquitectonica and appointed with museum-quality art installations throughout.',
    mainImage: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800',
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800',
      'https://images.unsplash.com/photo-1600566753151-384129cf4d3a?w=800',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
    ],
    amenities: [
      'Private Yacht Dock',
      'Waterfront Pool',
      'Tennis Court',
      'Guest House',
      'Home Theater',
      'Chef\'s Kitchen',
      'Security System',
      'Staff Quarters',
    ],
    isLuxury: true,
    isFeatured: true,
    coordinates: { lat: 25.776, lng: -80.176 },
  },
  {
    id: 'prop-004',
    title: 'Brickell Apex Penthouse',
    price: 8750000,
    priceFormatted: '$8.75M',
    currency: 'USD',
    location: {
      city: 'Miami',
      country: 'USA',
      neighborhood: 'Brickell',
    },
    type: 'Penthouse',
    beds: 5,
    baths: 6,
    sqm: 780,
    status: 'pre-construction',
    isOffPlan: true,
    completionYear: 2026,
    developer: 'Related Group',
    description:
      'Perched atop the iconic Brickell Apex tower, this full-floor penthouse redefines urban luxury with wraparound terraces overlooking Biscayne Bay and the Miami skyline. Custom interiors by Roberto Cavalli Home feature hand-laid Calacatta marble, burnished bronze fixtures, and bespoke cabinetry throughout.',
    mainImage: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=800',
    ],
    amenities: [
      'Private Rooftop Pool',
      'Sky Lounge',
      'Concierge',
      'Valet',
      'Fitness Center',
      'Spa',
      'Private Elevator',
    ],
    isLuxury: true,
    isFeatured: true,
    coordinates: { lat: 25.758, lng: -80.193 },
  },
  {
    id: 'prop-005',
    title: 'Comporta Beach Villa',
    price: 6800000,
    priceFormatted: '€6.8M',
    currency: 'EUR',
    location: {
      city: 'Comporta',
      country: 'Portugal',
      neighborhood: 'Comporta Village',
    },
    type: 'Villa',
    beds: 6,
    baths: 7,
    sqm: 980,
    status: 'pre-construction',
    isOffPlan: true,
    completionYear: 2026,
    developer: 'Vanguard Properties',
    description:
      'Nestled among maritime pine forests just steps from Comporta\'s pristine Atlantic beaches, this contemporary villa celebrates the region\'s natural beauty with rammed earth walls, local timber, and vast glazed living spaces that dissolve the boundary between indoors and nature. Portugal\'s Golden Visa program applies.',
    mainImage: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800',
    images: [
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800',
      'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800',
      'https://images.unsplash.com/photo-1598228723793-52759bba239c?w=800',
    ],
    amenities: [
      'Infinity Pool',
      'Private Beach Access',
      'Wine Cave',
      'Outdoor Kitchen',
      'Garden',
      'Garage',
      'Sustainable Energy',
    ],
    isLuxury: true,
    isFeatured: true,
    coordinates: { lat: 38.38, lng: -8.78 },
  },
  {
    id: 'prop-006',
    title: 'La Zagaleta Grand Villa',
    price: 18900000,
    priceFormatted: '€18.9M',
    currency: 'EUR',
    location: {
      city: 'Marbella',
      country: 'Spain',
      neighborhood: 'La Zagaleta',
    },
    type: 'Villa',
    beds: 8,
    baths: 10,
    sqm: 2100,
    status: 'resale',
    isOffPlan: false,
    description:
      'Presiding over La Zagaleta — Europe\'s most exclusive private residential resort — this palatial villa commands sweeping panoramas of the Mediterranean, Gibraltar, and the North African coastline. The estate unfolds across three manicured hectares with formal gardens, a championship-size tennis court, and a helicopter landing pad.',
    mainImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
      'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    ],
    amenities: [
      'Helipad',
      'Tennis Court',
      'Indoor Pool',
      'Outdoor Pool',
      'Cinema Room',
      'Cellar',
      'Staff Apartments',
      'Stables',
    ],
    isLuxury: true,
    isFeatured: true,
    coordinates: { lat: 36.549, lng: -4.958 },
  },
  {
    id: 'prop-007',
    title: 'One Hyde Park Lateral Apartment',
    price: 22000000,
    priceFormatted: '£22M',
    currency: 'GBP',
    location: {
      city: 'London',
      country: 'United Kingdom',
      neighborhood: 'Knightsbridge',
    },
    type: 'Apartment',
    beds: 4,
    baths: 5,
    sqm: 520,
    status: 'resale',
    isOffPlan: false,
    description:
      'A rare lateral apartment within One Hyde Park — the world\'s most prestigious address — offering unparalleled Hyde Park frontage and a level of security and service that rivals the finest private members\' club. Interiors by Candy & Candy are presented in immaculate condition with rare stone and custom millwork throughout.',
    mainImage: 'https://images.unsplash.com/photo-1600047509358-9dc75507daeb?w=800',
    images: [
      'https://images.unsplash.com/photo-1600047509358-9dc75507daeb?w=800',
      'https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?w=800',
      'https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=800',
    ],
    amenities: [
      'Residents-Only Pool',
      'Squash Courts',
      'Cinema',
      'Mandarin Oriental Services',
      '24/7 Concierge',
      'Panic Room',
      'Secure Parking',
    ],
    isLuxury: true,
    isFeatured: true,
    coordinates: { lat: 51.502, lng: -0.161 },
  },
  {
    id: 'prop-008',
    title: 'Uluwatu Clifftop Villa',
    price: 3400000,
    priceFormatted: '$3.4M',
    currency: 'USD',
    location: {
      city: 'Bali',
      country: 'Indonesia',
      neighborhood: 'Uluwatu',
    },
    type: 'Villa',
    beds: 5,
    baths: 6,
    sqm: 820,
    status: 'pre-construction',
    isOffPlan: true,
    completionYear: 2026,
    developer: 'Bali Signature Estates',
    description:
      'Cantilevering over dramatic sea cliffs at Bali\'s southern tip, this sculptural villa merges Balinese architectural tradition with contemporary resort living. Handcrafted from volcanic stone, reclaimed teak, and tropical hardwoods, with tiered infinity pools that appear to merge with the Indian Ocean horizon.',
    mainImage: 'https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=800',
    images: [
      'https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=800',
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800',
      'https://images.unsplash.com/photo-1596178065887-1198b6148b2b?w=800',
    ],
    amenities: [
      'Tiered Infinity Pool',
      'Ocean Terrace',
      'Yoga Pavilion',
      'Outdoor Shower',
      'Tropical Garden',
      'Staff Villa',
      'Surf Storage',
    ],
    isLuxury: true,
    isFeatured: true,
    coordinates: { lat: -8.83, lng: 115.088 },
  },
];

/* ─── Pre-Construction Projects ─────────────────────────────────────────────── */

export const PRE_CONSTRUCTION_PROJECTS: Project[] = [
  {
    id: 'proj-001',
    name: 'The Residences at Burj Binghatti',
    developer: 'Binghatti Developers',
    location: 'Business Bay',
    country: 'UAE',
    priceFrom: 2800000,
    priceTo: 15000000,
    units: 112,
    completionYear: 2026,
    status: 'Under Construction',
    paymentPlan: '60/40',
    description:
      'Destined to become the world\'s tallest residential tower, Burj Binghatti Jacob & Co Residences delivers an unmatched fusion of haute horology and architectural ambition. Interiors co-designed with Jacob & Co feature gem-inspired detailing and bespoke furnishing packages at every level.',
    coverImage: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800',
    amenities: [
      'Sky Infinity Pool',
      'Helipad',
      'Concierge',
      'Private Cinema',
      'Wellness Club',
      'Business Lounge',
      'Valet',
    ],
    highlights: [
      'World\'s tallest residential tower',
      'Jacob & Co branded interiors',
      '60/40 payment plan',
      'Dual residency eligibility',
      'Projected 8–12% rental yield',
    ],
  },
  {
    id: 'proj-002',
    name: 'Aeterna Residences Marbella',
    developer: 'Sierra Blanca Estates',
    location: 'Sierra Blanca',
    country: 'Spain',
    priceFrom: 3500000,
    priceTo: 9000000,
    units: 28,
    completionYear: 2026,
    status: 'Under Construction',
    paymentPlan: '50/50',
    description:
      'A collection of twenty-eight ultra-exclusive villas cascading down the slopes of Sierra Blanca with uninterrupted panoramas from the Mediterranean to Gibraltar. Designed by Rafael de La-Hoz with biophilic landscaping by Enzo Enea, each residence features private pools, automation by Savant, and custom Italian stone.',
    coverImage: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
    amenities: [
      'Private Pool',
      'Panoramic Views',
      'Smart Home',
      'Wine Cellar',
      'Cinema',
      'Gym',
      'Concierge Services',
    ],
    highlights: [
      'Gated community with 24/7 security',
      'Rafael de La-Hoz architecture',
      'Biophilic landscape design',
      'Golden Visa qualifying',
      'Completion Q4 2026',
    ],
  },
  {
    id: 'proj-003',
    name: 'Rosewood Residences Miami',
    developer: 'Related Group & Rosewood Hotels',
    location: 'Brickell',
    country: 'USA',
    priceFrom: 5500000,
    priceTo: 40000000,
    units: 90,
    completionYear: 2027,
    status: 'Launching Soon',
    paymentPlan: '30/70',
    description:
      'The first Rosewood Residences in the Americas brings the legendary Rosewood Hotels hospitality brand to Brickell, Miami\'s financial and cultural epicenter. Ninety sky residences occupy a slender tower by Arquitectonica with interiors by AvroKO, including the brand\'s signature Sense spa and curated art programming.',
    coverImage: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    amenities: [
      'Rosewood Sense Spa',
      'Signature Restaurant',
      'Residents\' Lounge',
      'Infinity Pool',
      'Art Curation',
      'Beach Club Access',
      'Concierge',
    ],
    highlights: [
      'Rosewood brand partnership',
      'First Rosewood Residences in the Americas',
      'AvroKO interior design',
      '30/70 payment plan',
      'Pre-launch priority pricing',
    ],
  },
  {
    id: 'proj-004',
    name: 'Alaia Residences Comporta',
    developer: 'Vanguard Properties',
    location: 'Comporta',
    country: 'Portugal',
    priceFrom: 1800000,
    priceTo: 7500000,
    units: 44,
    completionYear: 2025,
    status: 'Ready to Move',
    paymentPlan: '30/70',
    description:
      'A curated collection of forty-four eco-conscious residences set within 40 hectares of protected Comporta landscape, minutes from Europe\'s most pristine Atlantic beaches. Low-density planning, natural materials, and a Zero Carbon certification make Alaia a benchmark for sustainable luxury in Europe.',
    coverImage: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800',
    amenities: [
      'Beach Club',
      'Organic Farm',
      'Equestrian Center',
      'Spa',
      'Kids\' Club',
      'Padel Courts',
      'Bike Trails',
    ],
    highlights: [
      'Zero Carbon certification',
      'Golden Visa qualifying',
      'Ready to move in',
      'Beach club membership included',
      'Managed rental programme available',
    ],
  },
  {
    id: 'proj-005',
    name: 'Nusantara Residences Ubud',
    developer: 'Bali Signature Estates',
    location: 'Ubud',
    country: 'Indonesia',
    priceFrom: 650000,
    priceTo: 2800000,
    units: 36,
    completionYear: 2026,
    status: 'Under Construction',
    paymentPlan: '40/60',
    description:
      'Perched above the Ayung River valley in Bali\'s cultural heartland, Nusantara Residences unites traditional Balinese craftsmanship with contemporary resort architecture. Each villa is oriented to capture sunrise over the volcano and set within living terraced gardens tended by a resident horticultural team.',
    coverImage: 'https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=800',
    amenities: [
      'River Valley Views',
      'Infinity Pool',
      'Yoga Shala',
      'Ayurvedic Spa',
      'Organic Restaurant',
      'Art Studios',
      'Jungle Trek',
    ],
    highlights: [
      'Projected 15–18% annual rental returns',
      'Freehold Hak Milik title available',
      'Managed rental programme',
      '40/60 payment plan',
      'Balinese master craftsmen',
    ],
  },
  {
    id: 'proj-006',
    name: 'The Whiteley London',
    developer: 'MARK & CC Land',
    location: 'Bayswater',
    country: 'United Kingdom',
    priceFrom: 3200000,
    priceTo: 22000000,
    units: 139,
    completionYear: 2025,
    status: 'Ready to Move',
    paymentPlan: '10/90',
    description:
      'The most significant heritage regeneration project in London in a generation, The Whiteley transforms a Grade II-listed Victorian department store into 139 exceptional residences by Foster + Partners. Residents enjoy a Six Senses spa, cinema, and a curated mix of restaurants and boutiques within a landmark central London address.',
    coverImage: 'https://images.unsplash.com/photo-1600047509358-9dc75507daeb?w=800',
    amenities: [
      'Six Senses Spa',
      'Residents\' Cinema',
      'Concierge',
      'Underground Parking',
      'Curated Retail',
      'Heritage Gardens',
      'Dining',
    ],
    highlights: [
      'Foster + Partners architecture',
      'Grade II-listed heritage building',
      'Six Senses Spa & Wellness',
      'Ready to move in',
      'Zone 1 Central London',
    ],
  },
];

/* ─── Markets ────────────────────────────────────────────────────────────────── */

export const MARKETS: Market[] = [
  {
    name: 'Dubai',
    country: 'UAE',
    flag: '🇦🇪',
    avgPrice: 6800000,
    yoy: '+18.4%',
    listingCount: 2140,
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800',
  },
  {
    name: 'Miami',
    country: 'USA',
    flag: '🇺🇸',
    avgPrice: 11200000,
    yoy: '+9.7%',
    listingCount: 876,
    image: 'https://images.unsplash.com/photo-1533106497176-45ae19e68ba2?w=800',
  },
  {
    name: 'Lisbon',
    country: 'Portugal',
    flag: '🇵🇹',
    avgPrice: 3400000,
    yoy: '+12.1%',
    listingCount: 542,
    image: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800',
  },
  {
    name: 'Marbella',
    country: 'Spain',
    flag: '🇪🇸',
    avgPrice: 8900000,
    yoy: '+15.3%',
    listingCount: 389,
    image: 'https://images.unsplash.com/photo-1559827291-72ee739d0d9a?w=800',
  },
  {
    name: 'London',
    country: 'United Kingdom',
    flag: '🇬🇧',
    avgPrice: 16500000,
    yoy: '+4.2%',
    listingCount: 1103,
    image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800',
  },
  {
    name: 'Bali',
    country: 'Indonesia',
    flag: '🇮🇩',
    avgPrice: 2100000,
    yoy: '+22.6%',
    listingCount: 218,
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800',
  },
];

/* ─── Stats ──────────────────────────────────────────────────────────────────── */

export const STATS: Stats = {
  totalListings: 5268,
  countries: 32,
  developers: 180,
  totalValue: '$48.2B',
};

/* ─── Testimonials ───────────────────────────────────────────────────────────── */

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 'test-001',
    name: 'Maximilian von Hartmann',
    role: 'Private Equity Partner, Frankfurt',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
    content:
      'Prestoni gave me access to off-market inventory in Dubai that simply isn\'t available anywhere else. From first enquiry to title transfer in 38 days — their white-glove team handled every detail flawlessly, including legal coordination across three jurisdictions.',
    property: 'Palm Jumeirah Signature Villa',
    location: 'Dubai, UAE',
    rating: 5,
  },
  {
    id: 'test-002',
    name: 'Isabella Carvalho',
    role: 'Tech Founder & Angel Investor, São Paulo',
    avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=200',
    content:
      'I invested in an off-plan penthouse through Prestoni in Brickell and the entire experience felt more like working with a private bank than a real estate platform. The market intelligence reports they provided were genuinely exceptional — comparable to tier-one investment research.',
    property: 'Brickell Apex Penthouse',
    location: 'Miami, USA',
    rating: 5,
  },
  {
    id: 'test-003',
    name: 'James Whitmore',
    role: 'Family Office Director, London',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200',
    content:
      'We\'ve worked with many prime property advisors over twenty years, but Prestoni stands alone for its international reach and discretion. They sourced a Comporta villa off-market, negotiated a 12% reduction, and managed the Portuguese Golden Visa application seamlessly alongside our legal counsel.',
    property: 'Comporta Beach Villa',
    location: 'Comporta, Portugal',
    rating: 5,
  },
];
